### ISSUE TITLE
TX1 Tensorflow low memory

### ISSUE THREAD

**Issue by stolam** [jetsonhacks/installTensorFlowJetsonTX#2]
Hi,

 am using jetson TX1 with CUDA 8.0, CUDNN 6.0 and Jetpack 3.1.
I installed tensorflow via the wheel provided by you to my python 3.5 virtualenv.

When I try to run tensorflow e.g. inception [example](https://www.tensorflow.org/tutorials/image_recognition), the python process gets killed because of lack of memory. It show info about GPU, but it seems it initializes on CPU and RAM. 

Another suspicion arises when I run pip list. There is `tensorflow (1.3.0)` not `tensorflow-gpu`.
Is it possible that the wheel was build incorrectly?

When I run the same example on my machine Nvidia 1080, 16 GB RAM, it only takes up to 2 GB of physical memory.

**Comment by jetsonhacks** [comment]
I do not know what is the cause of your issue. I would think that if you ran out of memory, then you would need to enable swap.

The instructions used to build the wheel is here: http://www.jetsonhacks.com/2017/09/18/build-tensorflow-on-nvidia-jetson-tx1-development-kit/
The scripts that were used to build the wheel are here: https://github.com/jetsonhacks/installTensorFlowTX1

You can build it yourself from source if you are concerned that the wheel is incorrect, or use some other method so that you are more comfortable with the results.

I know you are suspicious, but I'm not quite sure why you are comparing the nomenclature for a desktop build with the provided wheel file.

I am also not sure what your comparison means with a desktop machine, they are not the same. Are you not using GPU memory on your 1080? The Jetson only has 4GB of memory in a unified architecture. That means it shares GPU memory with CPU memory.

**Comment by stolam** [comment]
Thank you very much for your reply.
I have been following your instruction to enable to swapfile and we shall see, how it goes.

The reason I am comparing the nomenclature is that I do not understand all the details,.

I was using GPU memory on my 1080. I watched RAM utilization on my Desktop, because I thought that Jetson has also CPU and GPU memory as Desktop.

I had no idea, that the memory is unified in Jetson. I thought that when I run `tegrastats` the first column is CPU memory and the last one is GPU. So the memory is unified and the last column is GPU cores utilization?

**Comment by jetsonhacks** [comment]
tegrastats shows a variety of statistics:
cpu - CPU cores and frequency
EMC – memory controller
AVP – audio/video processor
VDE – video decoder engine
GR3D – GPU

GR3D : GPU, processor%@MHz
So it shows the CUDA cores load, and at what frequency.

You can ask on the NVIDIA Jetson forum: https://devtalk.nvidia.com/default/board/164/jetson-tx1/ 
if there are other TensorFlow implementations and wheel files which more closely suit your needs.

**Comment by stolam** [comment]
Thank you very much.
I also like your tutorials and youtube videos very much.
