### ISSUE TITLE
Session crash

### ISSUE THREAD

**Issue by ChloeEHKim** [jetsonhacks/installTensorFlowJetsonTX#3]
Hi 
Thank you for the repository, I was having so much problem with building tensorflow from source and I ended up here. 
I was able to successfully install tensorflow with wheel file(py27) on TX1.
However, It crashes immediately whenever I create a session, I think it's something to do with no NUMA nodes error. 
Can you help me out on this?
Thanks in advance.

**Comment by jetsonhacks** [comment]
The Jetson is an ARM based design, it does not have NUMA support. It is supposed to print out a NUMA error message indicating that NUMA is not available. It's hard to tell what the problem is based on the description.

**Comment by ChloeEHKim** [comment]
Yes, I know.
I think the reason for crashing is answered here.
https://stackoverflow.com/questions/39783919/tensorflow-on-nvidia-tx1/
Can you successfully create a session in tensorflow installed with the wheel file?

**Comment by jetsonhacks** [comment]
Here is an alternative, please use it: https://github.com/peterlee0127/tensorflow-tx2
You can also search for other alternatives, I know that members of the Jetson community use the Peter Lee version successfully.

To be clear, I do not understand your question. Here is the article and video showing installation: http://www.jetsonhacks.com/2017/09/22/install-tensorflow-python-nvidia-jetson-tx-dev-kits/
There are also articles available on the website for building TensorFlow from source on the Jetson TX1.

The .whl files here have been tested on both the TX1 and the TX2 with both version of Python. 

When reporting issues on Github, it is expected that you  provide information to the developer on how to recreate your issue.

Since you do not give any information about which version of CUDA or cuDNN you have installed, the version of L4T you are running,  or any other information about how to recreate the issue you have encountered,  I am unable to help.
